DROP TABLE IF EXISTS MemberEvent;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS AcademicYear;
DROP TABLE IF EXISTS Semester;

DROP VIEW IF EXISTS Membership;
DROP VIEW IF EXISTS Recent_Events;
DROP VIEW IF EXISTS Semester_Overview;